package _4.fortuna_reports.entitymanager.exceptions

class UserAlreadyExistsException(message: String): RuntimeException(message)